CREATE TABLE COORDINATOR
(
    cood_num NUMBER(10) NOT NULL,
    cood_id VARCHAR2(20) NOT NULL,
    cood_pw VARCHAR2(15) NOT NULL,
    cood_name VARCHAR(20) NOT NULL
);

CREATE TABLE DOCTORS
(
    doc_num NUMBER(10) NOT NULL,
    doc_id VARCHAR2(20) NOT NULL,
    doc_pw VARCHAR2(15) NOT NULL,
    doc_email VARCHAR2(50),
    doc_name varchar2(20) NOT NULL
);

CREATE TABLE PATIENTS (
    PAT_NUM NUMBER PRIMARY KEY,
    PAT_ID VARCHAR2(50) UNIQUE NOT NULL,
    PAT_PW VARCHAR2(50) NOT NULL,
    PAT_NAME VARCHAR2(100) NOT NULL,
    PAT_PHONE VARCHAR2(20),
    PAT_BIRTH DATE,
    PAT_GEN VARCHAR2(10),
    PAT_EMAIL VARCHAR2(100),
    PAT_ADDR VARCHAR2(255)
);

CREATE TABLE EMR (
    EMR_NUM NUMBER PRIMARY KEY,
    EMR_CONTENTS VARCHAR2(1000) NOT NULL,
    EMR_PMH VARCHAR2(100),
    EMR_DATE date default sysdate NOT NULL,
    DOC_ID_FK VARCHAR2(20),
    PAT_NUM_FK NUMBER(10),
    CONSTRAINT FK_DOCTOR FOREIGN KEY (DOC_ID_FK) REFERENCES DOCTORS(DOC_ID),
    CONSTRAINT FK_PATIENT FOREIGN KEY (PAT_NUM_FK) REFERENCES PATIENTS(PAT_NUM)
);


CREATE TABLE REVIEW_BOARD (
    RB_NUM NUMBER PRIMARY KEY,
    RB_TITLE VARCHAR2(200),
    RB_CONTENTS VARCHAR2(2000),
    RB_POSTDATE date DEFAULT sysdate NOT NULL,
    RB_OFILE VARCHAR2(200),
    RB_SFILE VARCHAR2(30),
    RB_VISITCOUNT NUMBER DEFAULT 0 NOT NULL,
    PAT_NUM_FK NUMBER(10),
    CONSTRAINT FK_REVIEW_PATIENT FOREIGN KEY (PAT_NUM_FK) REFERENCES PATIENTS(PAT_NUM)
);

-- ALTER TABLE EMR MODIFY EMR_DATE date default sysdate NOT NULL;

-- ALTER TABLE Doctors
--     ADD CONSTRAINT doc_id_pk PRIMARY key(doc_id);
--
-- ALTER TABLE PATIENTS
--     ADD CONSTRAINT pat_num_pk PRIMARY key(pat_num);
--
-- ALTER TABLE COORDINATOR
--     ADD CONSTRAINT cood_num_pk PRIMARY key(cood_num);
--
-- INSERT INTO COORDINATOR
-- VALUES (900000, 'jiho', '0815', '최지호');
-- INSERT INTO COORDINATOR
-- VALUES (900001, 'minddo', '0919','허민석');
-- INSERT INTO DOCTORS
-- VALUES (800001, 'hansohee', '1118','hsh1118@gmail.com','한소희');
--
-- ALTER TABLE PATIENTS MODIFY PAT_GEN VARCHAR2(15);
--
-- delete from PATIENTS where PAT_NAME = '환자';


